import { Inter } from "next/font/google";
import { Roboto_Mono } from "next/font/google";
import styles from "./page.module.css";
import Image from "next/image";
import Link from "next/link";
import Navbar from "./components/navbar";



import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const roboto_mono = Roboto_Mono({subsets: ["latin"]});

export const metadata = {
  title: "Creative Labs SC",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={roboto_mono.className} style={{height:'100%'}}>
        <body className={roboto_mono.className} style={{height:'100%'}}>
          <Navbar/>
          {children}
        </body>
    </html>
  );
}
